Created a cpp file in Bestpractice folder.
Vitaljaz/hacktoberfest pull request #2
Opened 2021-10-02 16:10 UTC by Abhishek07-0302

2021-10-02 17:20 UTC, Vitaljaz requested changes
Good, but need small refactoring

2021-10-02 17:20 UTC, Vitaljaz commented on 2021/C-Plus-Plus/BestPractice/hello_world.cpp
> +#include<bits/stdc++.h>
better: `iostream`

2021-10-02 17:20 UTC, Vitaljaz commented on 2021/C-Plus-Plus/BestPractice/hello_world.cpp
> +int main(){
need correct white spaces for good reading

2021-10-02 18:14 UTC, Vitaljaz requested changes

2021-10-02 18:14 UTC, Vitaljaz commented on 2021/C-Plus-Plus/BestPractice/hello_world.cpp
> +#include<iostream>
better: `#include <iostream>` with space

2021-10-02 18:14 UTC, Vitaljaz commented on 2021/C-Plus-Plus/BestPractice/hello_world.cpp
> +int main()
just:
```
int main() {
    std::cout << "Hello World!\n";
    return 0;
}
```

2021-10-02 18:23 UTC, Vitaljaz commented
@Abhishek07-0302 nice, you need star this repo

2021-10-02 18:34 UTC, Abhishek07-0302 commented
> @Abhishek07-0302 nice, you need star this repo

Done.

2021-10-02 18:45 UTC, merged

2021-10-04 08:42 UTC, Abhishek07-0302 commented
Please add hacktoberfest accepted tag. If possible.